import test from 'node:test';import assert from 'node:assert/strict';
import {defaultState,normalizeState,finishDay,pickDay,saveState,loadState,safeBackup,letterChoices,STORE_KEY} from '../js/core.js';
test('finishing a day preserves the other learner and advances only this learner',()=>{const state=defaultState();state.profiles.vivian.step=3;const next=finishDay(state,'anastasia',1);assert.deepEqual(next.profiles.anastasia.completed,[1]);assert.equal(next.profiles.anastasia.day,2);assert.equal(next.profiles.vivian.step,3);assert.deepEqual(state.profiles.anastasia.completed,[]);});
test('replaying a completed day does not duplicate or erase progress',()=>{let state=finishDay(defaultState(),'vivian',2);state=pickDay(state,'vivian',1);state=finishDay(state,'vivian',1);state=finishDay(state,'vivian',2);assert.deepEqual(state.profiles.vivian.completed,[1,2]);});
test('last day never runs past the curriculum',()=>{assert.equal(finishDay(defaultState(),'vivian',60).profiles.vivian.day,60);assert.throws(()=>pickDay(defaultState(),'vivian',61));});
test('corrupt and hostile state is normalized without trusting unknown fields',()=>{const d=normalizeState({version:1,activeProfile:'evil',profiles:{vivian:{day:900,step:-9,completed:[1,1,0,61,'4',3]}},settings:{rate:999}});assert.equal(d.activeProfile,null);assert.equal(d.profiles.vivian.day,60);assert.equal(d.profiles.vivian.step,0);assert.deepEqual(d.profiles.vivian.completed,[1,3]);assert.equal(d.settings.rate,1.05);});
test('local save/resume keeps the active activity',()=>{const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};const state=defaultState();state.profiles.vivian.step=4;state.activeProfile='vivian';assert(saveState(storage,state));assert.equal(loadState(storage).profiles.vivian.step,4);data.set(STORE_KEY,'broken');assert.equal(loadState(storage).profiles.vivian.step,0);});
test('backup import rejects unrelated files and clamps supported state',()=>{assert.throws(()=>safeBackup('{}'));assert.throws(()=>safeBackup('x'.repeat(250001)));assert.deepEqual(safeBackup(JSON.stringify(defaultState())),defaultState());});
test('every lowercase matching game includes its target exactly once',()=>{for(let code=97;code<=122;code++)for(let day=1;day<=60;day++){const target=String.fromCharCode(code),choices=letterChoices(target,day);assert.equal(new Set(choices).size,3);assert.equal(choices.filter(x=>x===target).length,1);}});
